### ISSUE TITLE
Failing shell demo_driver self-tests

### ISSUE THREAD

**Issue by PuneetMatharu** [oomph-lib/oomph-lib#12]
@alhazel, have you come across the following issue before/know what might be going on here? (@MatthiasHeilManchester said you were the man to ask.)

I was running the self-tests with my CMake build (with a macOS runner) and came across the following warnings/error in `demo_drivers/shell/circular_plate/`:
```
Running circular flat plate 

======================================================================
Oomph-lib WARNING

 at /Users/runner/work/oomph-lib/oomph-lib/src/generic/elements.cc:4504

 in FiniteElement::self_test()

--------------------------------------------------------

Determinant of Jacobian matrix is zero at ipt 0

======================================================================

======================================================================
Oomph-lib WARNING

 at /Users/runner/work/oomph-lib/oomph-lib/src/generic/elements.cc:4504

 in FiniteElement::self_test()

--------------------------------------------------------

Determinant of Jacobian matrix is zero at ipt 0

======================================================================

======================================================================
Oomph-lib ERROR

 at /Users/runner/work/oomph-lib/oomph-lib/demo_drivers/shell/circular_plate/unstructured_clamped_circular_plate.cc:2374

 in main()

--------------------------------------------------------
```
Interestingly, this doesn't happen every time I run the tests and it doesn't appear when I use a Linux runner. I suspect that it's due to `triangle` producing skewed triangles that collapse as a result of round-off errors on macOS, because of the lack of `fpu_control.h`, but I'm not sure. (We currently use a dummy header for Macs.) Link to the possibly related description in `oomph_triangle/triangle.c`:

https://github.com/oomph-lib/oomph-lib/blob/23b75400e4e777f62e694a22a261f17e81c94d22/external_src/oomph_triangle/triangle.c#L257-L273

If it doesn't ring any bells, I can try running that specific test a few times with `#define INEXACT volatile`, as Shewchuk recommends (in the linked comment block).

**Comment by alhazel** [comment]
This isn't familiar to me. I agree with your tentative diagnosis that this could be to do with round-off. I guess having a look at the mesh would reveal whether something funny has happened in the mesh generation. If you turn the warning off, does the test still pass or does it die?

**Comment by MatthiasHeilManchester** [comment]
When I discussed this with Puneet I spotted that both problem codes are (or seemed to be) ones that are based on Wassamon's subsequently abandoned attempt to come up with unstructured elements for fourth-order problems. I believe this has been superseded by David's work (which Aidan is in the process of reactivating and then merging in). In any case, I recall there being some serious questions about this bit of code anyway, so I wondered if it was actually cleaner to remove it from the public repository and keep it alive in the private one (if at all).

**Comment by alhazel** [comment]
I agree. There were questions about this code. Let's remove this from the repository. I don't think there is any need to keep it alive.

**Comment by PuneetMatharu** [comment]
@alhazel, I was able to disable the warning/error in the driver code and it ran perfectly well and passed the self-test. I'm not entirely sure what is going on. 

Which particular driver codes would you both recommend that I remove? (Apart from the `shell/circular_plate` driver.)

**Comment by alhazel** [comment]
In addition to the whole circular_plate directory you should remove
clamped_shell/unstructured_clamped_curved_shell.cc, associated mesh data and tests,
plate/unstructured_clamped_square_plate.cc, associated mesh data and tests. Oh the Makefiles will need updating to remove these drivers.

**Comment by PuneetMatharu** [comment]
Excellent, thanks!
