### ISSUE TITLE
Add version information (i.e. tags) to previous commits and settle on versioning strategy

### ISSUE THREAD

**Issue by puneetmatharu** [oomph-lib/oomph-lib#4]
Can we (i) add the previous version information to the repository and (ii) settle on a versioning strategy for future releases? 

For (i), we would simply need to compile a list of commit IDs associated with new release versions (possibly extracted from the change-log). Once we're all in agreement, we can add the tags to the repository. From the SVN information + Git log, I've managed to extract the following commit IDs (in reverse chronological order):

- 141b3b638a41e278199b3a337ac4dcf9522b2aba: no specific version but it states "This is now going to be the next release."
- f7b1a2a903085b6d09f48c47c6840d1e5caf88ed: no specific version but it contains "...this could be the long overdue next official release."
- fa98bbe89f35c8698e9159c3f376d8dcaf8ea9ab: release version, so v0.9.0 -> v1.0.0.
- b3cb313a812e265113f789d3cd3a5b43c31386dc: version v0.8.5 -> v0.9.0.

Are there any version changes that I'm missing @MatthiasHeilManchester, @alhazel? Alternatively, does anyone know a less painful way to extract the version information (i.e. not the SVN revision information)?

For (ii), I would propose that we adopt the [semantic versioning](https://semver.org/) strategy, where the version number has the form `MAJOR.MINOR.PATCH`. We would then increment the:

- `MAJOR` version when you make incompatible API changes,
- `MINOR` version when you add functionality in a backwards-compatible manner, and
- `PATCH` version when you make backwards-compatible bug fixes.

P.S. At some point in the future, I can create a pull request to add a [`bumpversion.cfg`](https://pypi.org/project/bumpversion/) that can manage the bumping of version information for us wherever required (i.e. it creates a commit with the new Git tag and edits selected files to update the contained version information).

**Comment by MatthiasHeilManchester** [comment]
Don't really care about the previous revisions but if you can label them (the ones that have numbers) then great. Re future numbering what you propose sounds perfectly sensible. I assume I ought to remove the svn revision number placeholder in the boilerplate licensing text at the top of all the source code. Would that have to be replaced by something else (in which case we might as well do it in one go)?

**Comment by PuneetMatharu** [comment]
I can label any commit at any point in time -- all I need is its commit ID. Excellent, and yes, I agree it would be a good idea to remove that [placeholder]. Personally, I don't think it's necessary, version information is easily accessible via the command-line and the Git Lens extension in VS Code. Unless anyone is against it, I would propose that it be removed entirely.

**Comment by MatthiasHeilManchester** [comment]
OK; I'll strip it out -- that can be my first proper exercise in interacting with the respository. Scary.

**Comment by PuneetMatharu** [comment]
Good luck!

**Comment by PuneetMatharu** [comment]
**Update:** the tags for version 0.9.0 and version 1.0.0 have been assigned. 
**Next step:** run the destruct tests and once they all pass, decide on a version number to assign to the current commit so we have a base to start the versioning from.

**Comment by MatthiasHeilManchester** [comment]
Not sure we necessarily want a version number for this just yet. Let's wait until people (who are not called Puneet or Jonathan) have actually started interacting with the repository.

**Comment by PuneetMatharu** [comment]
Got it! I'm in no rush - I thought it'd be useful to leave a comment here for what the next steps should (could?) be when we come back to this issue.
