### ISSUE TITLE
Update instructions for contributors

### ISSUE THREAD

**Issue by MatthiasHeilManchester** [oomph-lib/oomph-lib#60]
- [x] Tell them to add tags to their pull requests (text added; take screenshot next time we do it!)
- [x] Tell them to kill actions if not needed (polar bears, forests, and all that...).
- [x] Decide on a policy for how to resolve long-winded discussions emerging from pull requests (everything needs to be signed off, but there's sometimes a lot of stuff!). Add this to instructions.
- [x] Provide instructions for building/checking github-based documentation.

**Comment by puneetmatharu** [comment]
Done!
