### ISSUE TITLE
Incorrect deletion of raw pointers in matrices.cc using delete instead of delete[]

### ISSUE THREAD

**Issue by PuneetMatharu** [oomph-lib/oomph-lib#7]
During compilation, I noticed a warning coming from `matrices.cc` about raw arrays being deleted using `delete` rather than `delete[]`. This appears in the function `CRDoubleMatrix::global_matrix()`, where the arrays `dist_first_row` `dist_nrow_local`, `delete nnz_offset`, and `delete dist_nnz_pt` are allocated:

https://github.com/oomph-lib/oomph-lib/blob/b18a9bb91fdc7b3678c8ff49966a6d79736087cb/src/generic/matrices.cc#L2477-L2499

They are later deleted with the following:

https://github.com/oomph-lib/oomph-lib/blob/b18a9bb91fdc7b3678c8ff49966a6d79736087cb/src/generic/matrices.cc#L2556-L2559

Should I create a PR to fix this?

**Comment by MatthiasHeilManchester** [comment]
Yes please!

**Comment by PuneetMatharu** [comment]
Excellent, see the (repeatedly -- apologies) linked PR.
